[tools]
tuist = "4.88.0"
git-cliff = "2.10.1"
typos = "1.32.0"
node = "24.0.2"

[hooks]
postinstall = '''
git-cliff --init detailed
npm install --save-dev @commitlint/cli @commitlint/config-conventional
echo "export default {extends: ['@commitlint/config-conventional']};" > commitlint.config.mjs

cat <<EOF > .git/hooks/prepare-commit-msg
#!/usr/bin/env bash

MSG=\$(cat .git/COMMIT_EDITMSG)
echo \$MSG | npx commitlint
EOF

chmod +x .git/hooks/prepare-commit-msg

for p in node_modules package-lock.json package.json commitlint.config.mjs; do
  grep -qxF "$p" .gitignore 2>/dev/null || printf '%s\n' "$p" >> .gitignore
done
'''
